project:
  type: website
  output-dir: docs

website:
  sidebar:
    title: "Navigation"
    style: docked
    search: true
    alignment: left
    contents:
      - href: index.qmd
        text: "Index"
      - href: about.qmd
        text: "Motivation"
      - section: "Wandering"
        contents: exploration/*
        
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    mainfont: "EB Garamond"
    backgroundcolor: "#F9F9F9"
    link-external-icon: true
    smooth-scroll: true
    citations-hover: true
    footnotes-hover: true


execute:
  freeze: auto

