---
title: "Some of the many why's living rent-free in my head"
---

I am a graduate student in the quantitative social sciences which, from my vantage point as a somewhat-dedicated Twitter lurker, comes off as a hotbed of squabbles over competing methodologies and theories. My own (limited) experience with topics that cut across disciplinary lines, vague though these boundaries may be, has largely been...unpleasant. A major reason conversations break down is the often-opaque shield of disciplinary pecularities.^[It's such a coincidence that everyone in my out-group sucks.] And yet, there's surely mutually beneficial exchanges to be had. Looking at tough and seemingly unassailable problems from different angles has a way of inspiring breakthroughs. The platitude notwithstanding, different fields working on similar problem may already have pieced together different parts of the puzzle; as such, "being the first to show [x]" in one's narrow slice of the world probably isn't all that great and such duplication of effort should (ideally) be discouraged. Can looking past disciplinary hang-ups and making progress on building a shared understanding not just save (valuable) time and effort but also spark creative solutions and ideas? I'd wager yes, but making an effort possibly couldn't hurt. The goal here is mostly to share my thoughts on cool work that grabs me and to solicit hate mail from disciplinary gate-keepers ^[Haters are of course welcome, although I would rather be friends. Really.]. 

I've thought about the following problems, in some shape or form, for the past decade. To be clear, these are not _unanswered_ questions, and while some of the proposed answers seem reasonable, I do think there's more to be said. Some combination of youthful hubris and the need to write research papers to complete my degree has convinced me that I can, _maybe_, be this person. Here's an (incomplete) list:

* How do parents, well, parent? The copious amounts of viral parenting TikTok and Instagram reels, my window into a slice of this process, makes one thing abundantly clear: parenting is tough. The "How-To" parenting books business is certainly booming but, at the end of the day, there's really no agreed upon guidebook. So, how do we even know how to parent? Looking around, an important source of (un)wanted input seems to be our families and broader support network. When people from some segment of society respond to a media item with "did we all have the same childhood?!?!", it underscores the tepidity of promises to "break the cycle". It's probably more likely that we will simply pass on time-honored traditions of doing the Same Thing. If you got your elder sibling's clothes once they'd aged out of them, you probably understand, in a microcosm, the anodyne calculus behind this process of passing down clothes but also "behavior", "attitudes", and even "political beliefs". It's just easier this way. But we've, _literally_, sailed past a world where almost everyone dies in the village of their birth. People move, sometimes to another city, but also increasingly, to other countries, and as they move, they take their particular set of physical and social objects with them. Passing down physical objects is fine, but this intergenerational transmission of _social_ objects is often frowned upon and hubbub over assilimation infrequently comes to dominate the discourse. It sounds crazy, but this bewildering maze calls to me.

* How do people, in a more general capacity than parents, learn things about the world? A chance conversation with my neighbor results in me finding out about a new bakery opening in the neighborhood, but what about more consequential things, say, whether the U.S. is going to annex Canada next month? How do I form beliefs about this? Who do I trust? Does who I surround myself with, my social network, so to speak, influence what beliefs I form? It sounds reasonable that it should. Even if we have the world's knowledge at our fingertips, we're continually learning new information from our friends and colleagues. If everyone I hang out with happens to like Nickleback, repeated exposure to their music _may_ induce me to start liking it too, if only "ironically". And not all social networks necessarily look alike, even with the same people in each. We _relate_ to people in different ways, a process mediated, in part, by our personalities, and so the flow of information, or the types of sharing can be quite different. The architecture of our social networks captures some of this, but what does knowing an architecture give you? What can you say about influence, or how information will flow in response to some event?

* You learn all sorts of neat quantitative tools as a quantitative researcher, but to use them, you really need to associate numbers with objects which, in my part of the academe, generally corresponds to some notion of value. Valuing things that already have prices is relatively straightforward, but how do we value stuff that _doesn't_ have prices or is just too abstract? There's no product listing on Amazon for living in a neighborhood with a score of 2 on the Air Quality Health Index. One can, of course, just look up housing prices for neighborhoods with good air quality on Zillow, but that price probably captures a bunch of other stuff, like good schools close-by or a high walkability score, so backing out the air quality valuation is not really obvious. You're probably thinking this entire edifice is rotten, but some researchers seem to (strongly) think otherwise.^[Their approach uses a fair bit of math, which probably inhibits its readability. I'm working on a post which compactly lays out their argument.] Why should we care how much people value air quality or noise pollution, anyway? Shouldn't we just be striving for high air quality and low noise pollution everywhere? In short, yes, but absent this, people of an accounting bent need these values for (distasteful) planning purposes^[What is the the [statistical value of your life](https://law.vanderbilt.edu/phd/faculty/w-kip-viscusi/368_Value_of_Statistical_Life_Oxford.pdf)?], and it's surely better for these values to be reasonable than not.

If any of this spiel speaks to you, or if you think I'm an idiot because [x] has already said the final word on any of these loose research hangers, feel free to reach out!